### ISSUE TITLE
Malformed response with 'type' model attribute

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#88] opened 2015-07-15 18:55 UTC
A rather peculiar issue here.

I've got a model with an attribute called type. Ember-data sends the following (stripped down) JSON API payload to the server.

```
{  
   "data":{  
      "attributes":{ 
         "type":"basic-question"
      },
      "relationships":{  
        ...
      },
      "type":"questions"
   }
}
```

Fortune saves the correct data to the database. But then...
I get the following response from fortune:
```
{  
   "data":{  
      "id":"5Qf6SS5Q6jnkLbaJ6DQx",
      "attributes":{  
         "type":"questions"
      },
      "relationships":{  
         ...
      },
      "links":{  
         "self":"/questions/5Qf6SS5Q6jnkLbaJ6DQx"
      }
   }
}
```

What happened here is the type (which should be within "data") is nowhere to be seen. Meanwhile the model attribute "type" has got the value which is actually the type that should be at the "data" level!

Not sure yet what's going wrong yet, but it seems fortune doesn't like "type" as a model attribute.

**Comment by 0x8890** [comment] 2015-07-15 19:06
This is probably a bug in the json api serializer, [the problem is probably in this function](https://github.com/fortunejs/fortune/blob/master/lib/serializer/serializers/json_api/helpers.js#L114). I think there was discussion previously in the json api repo issues about this very topic (using reserved keywords as attributes), and the authors seemed to be against it because it causes implementation issues such as right now :(

**Comment by nickschot** [comment] 2015-07-15 19:11
I thought something like that.. but I can't find a list of reserved keywords anywhere in the specification. Do you happen to know more about that?

**Comment by 0x8890** [comment] 2015-07-15 19:12
Formally, no the JSON API spec doesn't track reserved keywords. Informally, [I keep a record of every reserved keyword used in the spec](https://github.com/fortunejs/fortune/blob/master/lib/serializer/serializers/json_api/settings.js).

**Comment by nickschot** [comment] 2015-07-15 19:28
From this discussion: https://github.com/json-api/json-api/issues/573

It seems that "attributes" was specifically added to the specification to counter any problems with reserved keywords. So this issue should be fixable.

**Comment by 0x8890** [comment] 2015-07-15 20:10
It's absolutely fixable, fixed in [this commit](https://github.com/fortunejs/fortune/commit/6b77305af25ca70cbbc3cf53df37ddbea665f295) and added a test case.

**Closed by 0x8890** 2015-07-15 20:10 UTC

**Comment by nickschot** [comment] 2015-07-15 20:17
Excellent! Nice work.
