### ISSUE TITLE
Weird ids breaks route

### ISSUE THREAD

**Issue by jlcarvalho** [fortunejs/fortune#130] opened 2015-09-10 05:02 UTC
I got this generated id: `/f9XL5u+VDM426bToRc1`.
So, when i tried to access `GET /people//f9XL5u+VDM426bToRc1` i got:

```json
{
    "errors": [
        {
            "title": "NotFoundError",
            "detail": "The field \"f9XL5u+VDM426bToRc1\" is not a link on the type \"people\"."
        }
    ]
}
```

**Comment by jlcarvalho** [comment] 2015-09-10 05:16
Again `LvHdwDFA/d/1uSscKNmw`and again `O/hYIlwLjUChLAm73dhG`.

I'm using Fortune.request to create these documents.

```js
const store = fortune.create({
  adapter: {
    type: mongodbAdapter,
    options: {
      url: config.database
    }
  },
  serializers: [ {
    type: MySerializer
  } ]
})

store.request({
  method: methods.create,
  type: 'people',
  payload: [{
    name: record.name,
    email: record.email
  }]
}).then(function (res) {
  console.dir(res.payload[0].id)
})
```

**Comment by jlcarvalho** [comment] 2015-09-10 05:37
In fact, this is a bug in the mongodb adapter. Here is the issue (https://github.com/fortunejs/fortune-mongodb/issues/14) in the right repo.

**Comment by 0x8890** [comment] 2015-09-10 06:32
The value of the ID should not matter actually! The problem is URI encoding. I see that you are using a custom `MySerializer`, which may not be encoding URIs properly. 

Here is testing for weird IDs:
https://github.com/fortunejs/fortune-json-api/blob/master/test/index.js#L232-L239
https://github.com/fortunejs/fortune-micro-api/blob/master/test/index.js#L56-L69

**Comment by jlcarvalho** [comment] 2015-09-10 13:31
My adapter extends the `JsonApiSerializer` which already handles this.

```
class MySerializer extends JsonApiSerializer {
    processRequest (context, request, response) {
        let ctx = super.processRequest(...arguments)

        if(request.url === '/users' && context.request.method === methods.create) return ctx

        let token = ctx.request.meta['x-access-token'];
        if (token) {
            let user = (deasync(jwt.verify)(token, app.get('superSecret')))

            if(!user){
                throw new errors.UnauthorizedError(`Falha ao validar o token.`)
            } else {
                ctx.request.session = user
                return ctx
            }
        } else {
            throw new errors.UnauthorizedError(`Token não informado.`)
        }
    }
}
```

**Comment by 0x8890** [comment] 2015-09-10 13:39
Are you sure your request URLs are encoded? I don't think this is a server-side problem.

**Comment by jlcarvalho** [comment] 2015-09-10 14:10
You're right. The client is not configured to encode URI. I thought that the IDs are encoded on the server response.

**Comment by 0x8890** [comment] 2015-09-10 14:14
The IDs are plaintext, but the URIs should be encoded, correct me if I'm wrong but I'll close this issue now. You should generally rely on the URIs provided by the server, the client does not need to build URIs.

**Closed by 0x8890** 2015-09-10 14:14 UTC

**Comment by jlcarvalho** [comment] 2015-09-10 22:46
You're right. Thank you again, and sorry for the dumb questions.
